branches:
  only:
    - master

language: groovy

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk12
    - os: osx
      # El Capitan
      osx_image: xcode8
    - os: osx
      # Sierra
      osx_image: xcode9
    - os: osx
      # High Sierra
      osx_image: xcode10
    - os: osx
      # Mojave
      osx_image: xcode11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
