branches:
  only:
    - master

language: groovy

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk12
    - os: osx
      # El Capitan (macOS 10.11, JDK 1.8.0_92-b14)
      osx_image: xcode8
    - os: osx
      # Sierra (macOS 10.12, JDK 1.8.0_112-b16)
      osx_image: xcode9
    - os: osx
      # High Sierra (macOS 10.13, JDK 10.0.2+13)
      osx_image: xcode10
    - os: osx
      # Mojave (macOS 10.14, JDK 12.0.2)
      osx_image: xcode11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
